### ISSUE TITLE
HAL implementation

### ISSUE THREAD

**Issue by p3p** [bobc/Marlin#1]
Thank you for the initial work you have done with the HAL it made me stop procrastinating and port Marlin over to a NUCLEO F746ZG, managed to get the majority (I needed) working without much effort, I have hit one issue that I don't know the source of and that is acceleration and deceleration are being completed at an almost constant block initial_rate, MultiU32X32toH32 is returning values that are far to small, in this case 256 times to small, I can fudge this and make the printer work, but I was curious if you had an idea of the source of the issue. It's probably a timer problem but I'm not sure where its propagating from.

**Comment by chrissbarr** [comment]
@p3p any chance the work you've done so far is available somewhere? I've just started trying to port to an F4-based control board, and I'd be very interested in seeing how you've tackled things.

I'm not so far as to be testing this stuff just yet, but I'll post an update if I run into any trouble with the MultiU32x32toH32 function.

**Comment by p3p** [comment]
@chrissbarr I've put my code up for you to have a look at (https://github.com/p3p/Marlin), I specifically targeted standard ramps features to get my printer working so any other config will probably fail. It's a very hacky port as I just wanted to prove to myself it would work.

**Comment by p3p** [comment]
After going back to figure this out,I think the problem is with the macro (though I may be wrong) , the 24bit rshift in the original macro is to remove the precision that was needed from the steps per timer tick calculation [here](https://github.com/bobc/Marlin/blob/b6a7027452cbfa982d27d7f6db9c5c6e0f0f5493/Marlin/planner.cpp#L1126). So changing the rshift to 32bit without modifying the multiplier doesn't seem to make sense, although I'm unsure of the purpose of the extra addition that was also added.

**Comment by chrissbarr** [comment]
@p3p thanks for putting your code online! We must have different standards, I wouldn't call your work hacky at all - it's much neater than the way I started off going about things.

I've gotten most of my F4 board working using the same structure you have, I think you've saved me a lot of time trying to figure out how to architect things. My original layout had Marlin within the structure generated by the CubeMX project, rather than your way of having the CubeMX structure inside Marlin - your way makes way more sense, keeping compatibility with other Marlin repos.

I'm using USB-CDC on my board instead of going via the UART, which has taken me a while to figure out but I think I have it all working now. I haven't had a chance to play with any stepper stuff yet as I have to get SPI and a TMC2x library working first, but once I do I'll see what happens with that macro.

So far 90% of my code is the same as yours, but what I've got is available here if it's any help:

https://github.com/chrissbarr/Marlin/tree/32-Bit-RCBugFix-F446VE

**Comment by p3p** [comment]
I was trying to keep the devices HAL something that could just be dropped in to the Marlin structure, bobc has done a great job with the abstraction, the only issues were a few Arduino dependencies that need to be implemented, The Print class being the most annoying. Got my first prints out of the STMF7 working really well at 60k stepper interrupts/sec (nothing is optimised), my printer is a hybrid (diy mini router) so its only going 150mm/s (1000mms^2). Can start tidying up the code now and adding the extra features I wanted (gcode via TCP (telnet)). Glad my code has been of some help.
